export {default as IconList} from './iconList'
export {default as TextSection} from './textSection'
export {default as SplitContent} from './splitContent'
export {default as ValpropList} from './valpropList'
export {default as FaqList} from './faqList'
export {default as ImageSection} from './imageSection'
export {default as CtaSection} from './ctaSection'
